# Generated by Django 4.2.6 on 2023-10-18 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("adApp", "0003_remove_listdetails_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listdetails",
            name="due_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
